# Generated by Django 4.2.2 on 2023-07-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_name_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
